apiVersion: v1
kind: Service
metadata:
  name: {{ include "kafkaclient.fullname" . }}
  labels:
    {{- include "kafkaclient.labels" . | nindent 4 }}
  annotations:
  {{ toYaml .Values.service.annotations | indent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
{{- if .Values.service.loadBalancerIP }}
  loadBalancerIP: {{ .Values.service.loadBalancerIP }}
{{- end }}
  selector:
    {{- include "kafkaclient.selectorLabels" . | nindent 4 }}
