apiVersion: v1
kind: ConfigMap
metadata:
  name: asyncapijson-config
  namespace: {{ .Values.configMapRef.namespace }}
  labels:
    app.kubernetes.io/name: argocd
data:
    database_name: "djangodb"
    database_port: 3306
    database_host: "10.101.251.199"