apiVersion: v1
kind: ConfigMap
metadata:
  name: asyncapijson-config
  namespace: {{ .Values.configMapRef.namespace }}
data:
  DATABASE_NAME: "djangodb"
  DATABASE_PORT: "3306"
  DATABASE_HOST: "10.101.251.199"