apiVersion: v1
kind: Secret
metadata:
  name: asyncapijson-secrets
type: Opaque
data:
 DATABASE_USER : {{ .Values.secretRef.data.DATABASE_USER | quote}}
 DATABASE_PASSWORD: {{ .Values.secretRef.data.DATABASE_PASSWORD | quote}}