apiVersion: v1
kind: Secret
metadata:
  name: asyncapijson-secrets
type: Opaque
data:
 DATABASE_USER : {{ .Values.secretRef.data.DATABASE_USER | b64enc | quote}}
 DATABASE_PASSWORD: {{ .Values.configMapRef.data.DATABASE_PASSWORD | b64enc | quote}}